capstone_monthly:
  target: bigquery_dev
  outputs:
    bigquery_dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('DBT_BIGQUERY_DATASET', env_var('GCP_BIGQUERY_ANALYTICS_DATASET', 'analytics')) }}"
      location: "{{ env_var('GCP_LOCATION', 'EU') }}"
      priority: interactive
      threads: 4
